### ISSUE TITLE
Question about dependencies in conda.recipe/meta.yaml

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Brain#20]
@hdoupe and @andersonfrailey, I don't understand the following Tax-Brain requirements specification:
```
requirements:
  build:
    - python
    - "taxcalc>1.0.0"
    - "behresp>=0.6.0"
    - "pandas>=0.23"
    - dask
    - "numpy>=1.13"

  run:
    - python
    - "taxcalc>1.0.0"
    - "behresp>=0.6.0"
    - "pandas>=0.23"
    - dask
    - "numpy>=1.13"
```
Can't you drop out the `pandas` and `numpy` lines from both sets of dependencies?
It would seem that they are redundant (and could cause dependency conflicts in the future) because `taxcalc` already lists `pandas` and `numpy` as requirements.  Certainly, the `behresp` packages, which make use of both `numpy` and `pandas`, are made just fine with using this pared-down set of requirements:
```
requirements:
  build:
    - python
    - "taxcalc>=1.0"

  run:
    - python
    - "taxcalc>=1.0"
```
